#!/usr/bin/env bash

# Check if nixfmt is installed
if ! command -v nixfmt &> /dev/null
then
    echo "error: nixfmt is not installed."
    exit 1
fi

# Get a list of staged files
staged_files=$(git diff --cached --name-only --diff-filter=ACMR | grep -v lock)

# If there are no staged files, exit successfully
if [ -z "$staged_files" ]; then
  exit 0
fi

# Format the staged files using prettier
echo "running nixfmt on staged files..."
nixfmt $staged_files

if [ $? -ne 0 ]; then
  echo "error: nixfmt formatting failed."
  exit 1
fi

# Add the formatted files back to the staging area
git add $staged_files

echo "formatting complete"
exit 0
